//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sales()
        {
            this.SaleDetail = new HashSet<SaleDetail>();
        }
    
        public int IdSale { get; set; }
        public string InvoiceNumber { get; set; }
        public int IdCompany { get; set; }
        public int IdUser { get; set; }
        public System.DateTime SaleDate { get; set; }
        public double SubTotalAmount { get; set; }
        public double TaxTotalAmount { get; set; }
        public double TotalAmount { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Companies Companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleDetail> SaleDetail { get; set; }
        public virtual Users Users { get; set; }
    }
}
